### ISSUE TITLE
"ValueError: Expecting Property Name" while building

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1146]
Followed the Build Instructions in the README which resulted with the following on fd27be8 (master):

```
(env) user@dev:~/matrix-doc$ ./scripts/gendoc.py 
gendoc: Building spec [targets=['index', 'push_gateway', 'client_server', 'application_service', 'identity_service', 'intro', 'appendices', 'server_server']]
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_index.rst
gendoc: > index.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_push_gateway.rst
gendoc: > push_gateway.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_client_server.rst
gendoc: > client_server_api.rst
gendoc: >> events.rst
gendoc: >> modules.rst
gendoc: >>> feature_profiles.rst
gendoc: >>> modules/instant_messaging.rst
gendoc: >>> modules/voip_events.rst
gendoc: >>> modules/typing_notifications.rst
gendoc: >>> modules/receipts.rst
gendoc: >>> modules/presence.rst
gendoc: >>> modules/content_repo.rst
gendoc: >>> modules/send_to_device.rst
gendoc: >>> modules/device_management.rst
gendoc: >>> modules/end_to_end_encryption.rst
gendoc: >>> modules/history_visibility.rst
gendoc: >>> modules/push.rst
gendoc: >>> modules/third_party_invites.rst
gendoc: >>> modules/search.rst
gendoc: >>> modules/guest_access.rst
gendoc: >>> modules/room_previews.rst
gendoc: >>> modules/tags.rst
gendoc: >>> modules/account_data.rst
gendoc: >>> modules/admin.rst
gendoc: >>> modules/event_context.rst
gendoc: >>> modules/cas_login.rst
gendoc: >>> modules/dm.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_application_service.rst
gendoc: > application_service_api.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_identity_service.rst
gendoc: > identity_service_api.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_intro.rst
gendoc: > intro.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_appendices.rst
gendoc: > appendices.rst
gendoc: > appendices/base64.rst
gendoc: > appendices/signing_json.rst
gendoc: > appendices/identifier_grammar.rst
gendoc: > appendices/threepids.rst
gendoc: > appendices/threat_model.rst
gendoc: > appendices/test_vectors.rst
gendoc: Building templated file /home/user/matrix-doc/scripts/tmp/templated_server_server.rst
gendoc: > server_server_api.rst
gendoc: EXEC: python /home/user/matrix-doc/scripts/templating/build.py -o /home/user/matrix-doc/scripts/tmp -i matrix_templates --substitution=%CLIENT_RELEASE_LABEL%=unstable --substitution=%CLIENT_MAJOR_VERSION%=r0 --substitution=%SERVER_RELEASE_LABEL%=unstable --substitution=%SERVER_MAJOR_VERSION%=unstable /home/user/matrix-doc/scripts/tmp/templated_index.rst /home/user/matrix-doc/scripts/tmp/templated_push_gateway.rst /home/user/matrix-doc/scripts/tmp/templated_client_server.rst /home/user/matrix-doc/scripts/tmp/templated_application_service.rst /home/user/matrix-doc/scripts/tmp/templated_identity_service.rst /home/user/matrix-doc/scripts/tmp/templated_intro.rst /home/user/matrix-doc/scripts/tmp/templated_appendices.rst /home/user/matrix-doc/scripts/tmp/templated_server_server.rst
gendoc:  ==== build.py output ==== 
INFO:matrix_templates.units:Reading event schema: /home/user/matrix-doc/event-schemas/schema/core-event-schema/event.yaml
INFO:matrix_templates.units:Reading event schema: /home/user/matrix-doc/event-schemas/schema/core-event-schema/room_event.yaml
INFO:matrix_templates.units:Reading event schema: /home/user/matrix-doc/event-schemas/schema/core-event-schema/state_event.yaml
Traceback (most recent call last):
  File "/home/user/matrix-doc/scripts/templating/build.py", line 284, in <module>
    substitutions=substitutions, verbose=args.verbose
  File "/home/user/matrix-doc/scripts/templating/build.py", line 161, in main
    substitutions=substitutions,
  File "/home/user/matrix-doc/scripts/templating/batesian/units.py", line 56, in get_units
    unit_dict[unit_key] = func()
  File "/home/user/matrix-doc/scripts/templating/matrix_templates/units.py", line 699, in load_event_examples
    example = json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 7 column 3 (char 160)
Traceback (most recent call last):
  File "./scripts/gendoc.py", line 545, in <module>
    exit (main(args.target or ["all"], args.dest, args.nodelete, substitutions))
  File "./scripts/gendoc.py", line 444, in main
    run_through_template(templated_files.values(), VERBOSE, substitutions)
  File "./scripts/gendoc.py", line 310, in run_through_template
    subprocess.check_call(args)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/user/matrix-doc/scripts/templating/build.py', '-o', '/home/user/matrix-doc/scripts/tmp', '-i', 'matrix_templates', '--substitution=%CLIENT_RELEASE_LABEL%=unstable', '--substitution=%CLIENT_MAJOR_VERSION%=r0', '--substitution=%SERVER_RELEASE_LABEL%=unstable', '--substitution=%SERVER_MAJOR_VERSION%=unstable', '/home/user/matrix-doc/scripts/tmp/templated_index.rst', '/home/user/matrix-doc/scripts/tmp/templated_push_gateway.rst', '/home/user/matrix-doc/scripts/tmp/templated_client_server.rst', '/home/user/matrix-doc/scripts/tmp/templated_application_service.rst', '/home/user/matrix-doc/scripts/tmp/templated_identity_service.rst', '/home/user/matrix-doc/scripts/tmp/templated_intro.rst', '/home/user/matrix-doc/scripts/tmp/templated_appendices.rst', '/home/user/matrix-doc/scripts/tmp/templated_server_server.rst']' returned non-zero exit status 1
(env) user@dev:~/matrix-doc$ pip --version
pip 9.0.1 from /home/user/matrix-doc/env/local/lib/python2.7/site-packages (python 2.7)
(env) user@dev:~/matrix-doc$ env/bin/pip install -r scripts/requirements.txt
Requirement already satisfied: docutils>=0.14 in ./env/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 4))
Requirement already satisfied: pygments>=2.2.0 in ./env/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 5))
Requirement already satisfied: Jinja2>=2.9.6 in ./env/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 6))
Requirement already satisfied: jsonschema>=2.6.0 in ./env/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 7))
Requirement already satisfied: PyYAML>=3.12 in ./env/lib/python2.7/site-packages (from -r scripts/requirements.txt (line 8))
Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python2.7/site-packages (from Jinja2>=2.9.6->-r scripts/requirements.txt (line 6))
Requirement already satisfied: functools32; python_version == "2.7" in ./env/lib/python2.7/site-packages (from jsonschema>=2.6.0->-r scripts/requirements.txt (line 7))
(env) user@dev:~/matrix-doc$ virtualenv --version
15.1.0
(env) user@dev:~/matrix-doc$ 
```

Debian 9, not sure what the problem is exactly.

**Comment by richvdh** [comment]
Annoying that this wasn't picked up by the test scripts. That should be fixed by a36bd1a6d2f8d10d908764af7177e7e6a1aa21b4.
